### ISSUE TITLE
SIGSEGV on profile commands

### ISSUE THREAD

**Issue by rjloura** [joyent/conch-shell#160]
conch throws a SIGSEGV on `profile add` or `profile list` (and perhaps others.

```
$ conch profile list
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x73cfb2]

goroutine 1 [running]:
github.com/joyent/conch-shell/vendor/github.com/jawher/mow.cli/internal/flow.(*Step).Run(0xc42000f9b0, 0x7a0ba0, 0xa2bf60)
	/usr/home/buildbot/bb/master/workers/go-worker/conch-shell-release/src/github.com/joyent/conch-shell/vendor/github.com/jawher/mow.cli/internal/flow/flow.go:39 +0xda
github.com/joyent/conch-shell/vendor/github.com/jawher/mow.cli/internal/flow.(*Step).callDo.func1(0xc42000f9e0, 0x0, 0x0)
	/usr/home/buildbot/bb/master/workers/go-worker/conch-shell-release/src/github.com/joyent/conch-shell/vendor/github.com/jawher/mow.cli/internal/flow/flow.go:52 +0x4c
panic(0x7a0ba0, 0xa2bf60)
	/usr/local/go/src/runtime/panic.go:502 +0x229
main.main.func2()
	/usr/home/buildbot/bb/master/workers/go-worker/conch-shell-release/src/github.com/joyent/conch-shell/cmd/conch/conch.go:85 +0x172
github.com/joyent/conch-shell/vendor/github.com/jawher/mow.cli/internal/flow.(*Step).callDo(0xc42000f9e0, 0x0, 0x0)
	/usr/home/buildbot/bb/master/workers/go-worker/conch-shell-release/src/github.com/joyent/conch-shell/vendor/github.com/jawher/mow.cli/internal/flow/flow.go:55 +0x70
github.com/joyent/conch-shell/vendor/github.com/jawher/mow.cli/internal/flow.(*Step).Run(0xc42000f9e0, 0x0, 0x0)
	/usr/home/buildbot/bb/master/workers/go-worker/conch-shell-release/src/github.com/joyent/conch-shell/vendor/github.com/jawher/mow.cli/internal/flow/flow.go:25 +0x43
github.com/joyent/conch-shell/vendor/github.com/jawher/mow.cli/internal/flow.(*Step).Run(0xc420059ea8, 0x0, 0x0)
	/usr/home/buildbot/bb/master/workers/go-worker/conch-shell-release/src/github.com/joyent/conch-shell/vendor/github.com/jawher/mow.cli/internal/flow/flow.go:29 +0xc2
github.com/joyent/conch-shell/vendor/github.com/jawher/mow%2ecli.(*Cmd).parse(0xc420121e00, 0xc42000e0b0, 0x0, 0x0, 0xc420059ea8, 0xc42000fda0, 0xc42000fdd0, 0xc42012e180, 0xc420059b28)
	/usr/home/buildbot/bb/master/workers/go-worker/conch-shell-release/src/github.com/joyent/conch-shell/vendor/github.com/jawher/mow.cli/commands.go:496 +0x517
github.com/joyent/conch-shell/vendor/github.com/jawher/mow%2ecli.(*Cmd).parse(0xc420120f00, 0xc42000e0b0, 0x1, 0x1, 0xc420059ea8, 0xc42000f9e0, 0xc42000fa10, 0x428764, 0x828180)
	/usr/home/buildbot/bb/master/workers/go-worker/conch-shell-release/src/github.com/joyent/conch-shell/vendor/github.com/jawher/mow.cli/commands.go:510 +0x72e
github.com/joyent/conch-shell/vendor/github.com/jawher/mow%2ecli.(*Cmd).parse(0xc420120300, 0xc42000e0a0, 0x2, 0x2, 0xc420059ea8, 0xc420059ea8, 0xc42000f9b0, 0x1, 0xc42000f9b0)
	/usr/home/buildbot/bb/master/workers/go-worker/conch-shell-release/src/github.com/joyent/conch-shell/vendor/github.com/jawher/mow.cli/commands.go:510 +0x72e
github.com/joyent/conch-shell/vendor/github.com/jawher/mow%2ecli.(*Cli).parse(0xc420059f48, 0xc42000e0a0, 0x2, 0x2, 0xc420059ea8, 0xc420059ea8, 0xc42000f9b0, 0x80cc64, 0x6)
	/usr/home/buildbot/bb/master/workers/go-worker/conch-shell-release/src/github.com/joyent/conch-shell/vendor/github.com/jawher/mow.cli/cli.go:76 +0xf5
github.com/joyent/conch-shell/vendor/github.com/jawher/mow%2ecli.(*Cli).Run(0xc420059f48, 0xc42000e090, 0x3, 0x3, 0x8140e7, 0x19)
	/usr/home/buildbot/bb/master/workers/go-worker/conch-shell-release/src/github.com/joyent/conch-shell/vendor/github.com/jawher/mow.cli/cli.go:105 +0x142
main.main()
	/usr/home/buildbot/bb/master/workers/go-worker/conch-shell-release/src/github.com/joyent/conch-shell/cmd/conch/conch.go:112 +0x3de

```

**Comment by sungo** [comment]
This is occurring on 1.4.0 with the linux-amd64 build, yes?
