### ISSUE TITLE
conch-mbo segfaults on run

### ISSUE THREAD

**Issue by sungo** [joyent/conch-shell#25]
As of at least 4cab764, conch-mbo segfaults immediately on execution.

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x12faf35]

goroutine 1 [running]:
github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow%2ecli%2ev1.(*step).run(0xc4200736b0, 0x1466880, 0x17bdff0)
	/Users/mattcashner/src/go/src/github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow.cli.v1/flow.go:28 +0xd6
github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow%2ecli%2ev1.(*step).callDo.func1(0xc420073770, 0x0, 0x0)
	/Users/mattcashner/src/go/src/github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow.cli.v1/flow.go:41 +0x4c
panic(0x1466880, 0x17bdff0)
	/usr/local/Cellar/go/1.9.3/libexec/src/runtime/panic.go:491 +0x283
github.com/joyent/go-conch.(*Conch).GetUserSettings(0xc42007e780, 0xc42007e780, 0x17c5370, 0xc42007e780)
	/Users/mattcashner/src/go/src/github.com/joyent/go-conch/user.go:29 +0x105
github.com/joyent/go-conch.(*Conch).VerifyLogin(0xc42007e780, 0xc420073980, 0xc42003fb10)
	/Users/mattcashner/src/go/src/github.com/joyent/go-conch/conch.go:43 +0x59
main.main.func1()
	/Users/mattcashner/src/go/src/github.com/joyent/conch-shell/cmd/conch-mbo/conch-mbo.go:72 +0x206
github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow%2ecli%2ev1.(*step).callDo(0xc420073770, 0x0, 0x0)
	/Users/mattcashner/src/go/src/github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow.cli.v1/flow.go:44 +0x70
github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow%2ecli%2ev1.(*step).run(0xc420073770, 0x0, 0x0)
	/Users/mattcashner/src/go/src/github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow.cli.v1/flow.go:16 +0x43
github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow%2ecli%2ev1.(*step).run(0xc42003fe80, 0x0, 0x0)
	/Users/mattcashner/src/go/src/github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow.cli.v1/flow.go:20 +0xbe
github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow%2ecli%2ev1.(*Cmd).parse(0xc420096400, 0xc42000e1a0, 0x0, 0x0, 0xc42003fe80, 0xc42003fe80, 0xc4200736b0, 0xc420096401, 0xc4200736b0)
	/Users/mattcashner/src/go/src/github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow.cli.v1/commands.go:473 +0x529
github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow%2ecli%2ev1.(*Cli).parse(0xc42003ff60, 0xc42000e1a0, 0x0, 0x0, 0xc42003fe80, 0xc42003fe80, 0xc4200736b0, 0x4, 0x14ee272)
	/Users/mattcashner/src/go/src/github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow.cli.v1/cli.go:73 +0x102
github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow%2ecli%2ev1.(*Cli).Run(0xc42003ff60, 0xc42000e1a0, 0x1, 0x1, 0x14ee272, 0x11)
	/Users/mattcashner/src/go/src/github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow.cli.v1/cli.go:102 +0x134
main.main()
	/Users/mattcashner/src/go/src/github.com/joyent/conch-shell/cmd/conch-mbo/conch-mbo.go:392 +0x4b4
```

**Comment by sungo** [comment]
This no longer occurs. My bet is that it got fixed in joyent/go-conch#15, specifically now that it checks err before trying to operate on the maybe-nil response.
