### ISSUE TITLE
segfault when fetching device settings

### ISSUE THREAD

**Issue by daleghent** [joyent/conch-shell#34]
```
[daleg@iridium]~$ ./conch-snap.sh d 8VNGRD2 settings
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1289f45]

goroutine 1 [running]:
github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow%2ecli%2ev1.(*step).run(0xc420079680, 0x1379700, 0x15e0150)
	/Users/mattcashner/src/go/src/github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow.cli.v1/flow.go:28 +0xd6
github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow%2ecli%2ev1.(*step).run(0xc420079770, 0x1379700, 0x15e0150)
	/Users/mattcashner/src/go/src/github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow.cli.v1/flow.go:20 +0xbe
github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow%2ecli%2ev1.(*step).callDo.func1(0xc420079cb0, 0x0, 0x0)
	/Users/mattcashner/src/go/src/github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow.cli.v1/flow.go:41 +0x4c
panic(0x1379700, 0x15e0150)
	/usr/local/Cellar/go/1.9.3/libexec/src/runtime/panic.go:491 +0x283
github.com/joyent/conch-shell/vendor/github.com/joyent/go-conch.(*Conch).GetUserSettings(0xc4200845f0, 0xc4200845f0, 0xc420127780, 0xc4200845f0)
	/Users/mattcashner/src/go/src/github.com/joyent/conch-shell/vendor/github.com/joyent/go-conch/user.go:29 +0x105
github.com/joyent/conch-shell/vendor/github.com/joyent/go-conch.(*Conch).VerifyLogin(0xc4200845f0, 0x6, 0xc420012400)
	/Users/mattcashner/src/go/src/github.com/joyent/conch-shell/vendor/github.com/joyent/go-conch/conch.go:43 +0x59
github.com/joyent/conch-shell/pkg/util.BuildAPIAndVerifyLogin()
	/Users/mattcashner/src/go/src/github.com/joyent/conch-shell/pkg/util/util.go:74 +0x36
github.com/joyent/conch-shell/pkg/commands/internal/devices.Init.func1.1()
	/Users/mattcashner/src/go/src/github.com/joyent/conch-shell/pkg/commands/internal/devices/init.go:31 +0x2b
github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow%2ecli%2ev1.(*step).callDo(0xc420079cb0, 0x0, 0x0)
	/Users/mattcashner/src/go/src/github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow.cli.v1/flow.go:44 +0x70
github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow%2ecli%2ev1.(*step).run(0xc420079cb0, 0x0, 0x0)
	/Users/mattcashner/src/go/src/github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow.cli.v1/flow.go:16 +0x43
github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow%2ecli%2ev1.(*step).run(0xc420079740, 0x0, 0x0)
	/Users/mattcashner/src/go/src/github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow.cli.v1/flow.go:20 +0xbe
github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow%2ecli%2ev1.(*step).run(0xc420043e90, 0x0, 0x0)
	/Users/mattcashner/src/go/src/github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow.cli.v1/flow.go:20 +0xbe
github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow%2ecli%2ev1.(*Cmd).parse(0xc42009d000, 0xc42000e130, 0x0, 0x0, 0xc420043e90, 0xc420079cb0, 0xc420079ce0, 0x0, 0x0)
	/Users/mattcashner/src/go/src/github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow.cli.v1/commands.go:473 +0x529
github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow%2ecli%2ev1.(*Cmd).parse(0xc42009c600, 0xc42000e130, 0x1, 0x2, 0xc420043e90, 0xc420079740, 0xc420079770, 0xc42000c0b8, 0xc42000c0a8)
	/Users/mattcashner/src/go/src/github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow.cli.v1/commands.go:487 +0x7ad
github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow%2ecli%2ev1.(*Cmd).parse(0xc42009c400, 0xc42000e110, 0x3, 0x3, 0xc420043e90, 0xc420043e90, 0xc420079680, 0xc42009c401, 0xc420079680)
	/Users/mattcashner/src/go/src/github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow.cli.v1/commands.go:487 +0x7ad
github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow%2ecli%2ev1.(*Cli).parse(0xc420043f40, 0xc42000e110, 0x3, 0x3, 0xc420043e90, 0xc420043e90, 0xc420079680, 0x13e22ad, 0xc)
	/Users/mattcashner/src/go/src/github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow.cli.v1/cli.go:73 +0x102
github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow%2ecli%2ev1.(*Cli).Run(0xc420043f40, 0xc42000e100, 0x4, 0x4, 0x13ebc9e, 0x25)
	/Users/mattcashner/src/go/src/github.com/joyent/conch-shell/vendor/gopkg.in/jawher/mow.cli.v1/cli.go:102 +0x134
main.main()
	/Users/mattcashner/src/go/src/github.com/joyent/conch-shell/cmd/conch/conch.go:94 +0x464
```

**Comment by daleghent** [comment]
ok, it'll either work or crash at random times. The speed at which it does something is a clue perhaps: When it crashes, it'll seemingly hang for 5-8 seconds after issuing the command, then barf the stack trace. When it works, the response is more or less immediate.

**Comment by sungo** [comment]
I'm pretty sure what's happening here is that the API server is timing out for some reason.

I think the error handling in joyent/go-conch#15 will prevent the segfault and the better error logging in joyent/go-conch#16 will give you a better idea of what's going on.

Can you pull a new snap and see how that flies?
